name: Release with Asset

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove first line (PDF Download button)
        run: sed -i '1d' README.md

      - name: Build PDF from README.md
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: README.md
          output_dir: out
          theme: styles/custom.css
          extend_default_theme: false

      - name: Rename the PDF
        run: cp out/README.pdf pawee_tanti_resume.pdf

      - name: Create a Release with the asset
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: pawee_tanti_resume.pdf
